// /lib/auth.js â Zero-dependency auth (PBKDF2 + HMAC tokens)
//
// Uses Node.js built-in 'crypto' only. No bcrypt/jwt packages needed.
//
// Env vars required:
//   STAFF_USERNAME        â e.g. "pg"
//   STAFF_PASSWORD_HASH   â generated by hashPassword() below
//   AUTH_SECRET           â random 32+ char string for token signing
//
import { createHmac, pbkdf2Sync, randomBytes, timingSafeEqual } from 'crypto';

const SALT_LEN = 16;
const KEY_LEN = 64;
const ITERATIONS = 100_000;
const DIGEST = 'sha512';
const TOKEN_TTL = 24 * 60 * 60 * 1000; // 24 hours

// ---- Password hashing ----

export function hashPassword(plaintext) {
  const salt = randomBytes(SALT_LEN).toString('hex');
  const hash = pbkdf2Sync(plaintext, salt, ITERATIONS, KEY_LEN, DIGEST).toString('hex');
  return `${salt}:${hash}`;
}

export function verifyPassword(plaintext, stored) {
  const [salt, storedHash] = stored.split(':');
  if (!salt || !storedHash) return false;
  const hash = pbkdf2Sync(plaintext, salt, ITERATIONS, KEY_LEN, DIGEST).toString('hex');
  try {
    return timingSafeEqual(Buffer.from(hash, 'hex'), Buffer.from(storedHash, 'hex'));
  } catch {
    return false;
  }
}

// ---- Token creation & verification ----

function getSecret() {
  const s = process.env.AUTH_SECRET;
  if (!s || s.length < 16) throw new Error('AUTH_SECRET env var must be at least 16 characters');
  return s;
}

export function createToken(username) {
  const payload = JSON.stringify({
    sub: username,
    iat: Date.now(),
    exp: Date.now() + TOKEN_TTL,
  });
  const b64 = Buffer.from(payload).toString('base64url');
  const sig = createHmac('sha256', getSecret()).update(b64).digest('base64url');
  return `${b64}.${sig}`;
}

export function verifyToken(token) {
  if (!token || !token.includes('.')) return null;
  const [b64, sig] = token.split('.');
  const expectedSig = createHmac('sha256', getSecret()).update(b64).digest('base64url');
  try {
    if (!timingSafeEqual(Buffer.from(sig), Buffer.from(expectedSig))) return null;
  } catch {
    return null;
  }
  const payload = JSON.parse(Buffer.from(b64, 'base64url').toString());
  if (payload.exp < Date.now()) return null; // expired
  return payload;
}

// ---- Middleware helper ----

export function authenticateRequest(request) {
  // Check cookie first, then Authorization header
  const cookieHeader = request.headers.get('cookie') || '';
  const match = cookieHeader.match(/staff_token=([^;]+)/);
  let token = match?.[1];

  if (!token) {
    const auth = request.headers.get('authorization') || '';
    if (auth.startsWith('Bearer ')) token = auth.slice(7);
  }

  if (!token) return null;
  return verifyToken(token);
}
