import { NextResponse } from 'next/server';
import { getReviewStats, getPostStats, getPhotoUploads, getAnalyticsHistory, saveAnalyticsSnapshot } from '@/lib/gbp/automation-db';
import { generateWeeklyReport } from '@/lib/gbp/ai-engine';
import { sendBookingConfirmation } from '@/lib/email';

// GET â full analytics dashboard data
export async function GET() {
  const reviewStats = getReviewStats();
  const postStats = getPostStats();
  const photos = getPhotoUploads(10);
  const history = getAnalyticsHistory(30);

  const dashboard = {
    overview: {
      totalReviews: reviewStats.total,
      avgRating: reviewStats.avgRating,
      escalatedReviews: reviewStats.escalated,
      totalPostsPublished: postStats.totalPublished,
      totalPostsFailed: postStats.totalFailed,
      totalImpressions: postStats.totalImpressions,
      totalClicks: postStats.totalClicks,
      photosUploaded: photos.length,
    },
    reviewBreakdown: reviewStats.byCategory,
    postBreakdown: postStats.byType,
    recentPhotos: photos,
    history,
    generatedAt: new Date().toISOString(),
  };

  return NextResponse.json(dashboard);
}

// POST â generate and send weekly report
export async function POST(request) {
  try {
    const reviewStats = getReviewStats();
    const postStats = getPostStats();

    const metrics = {
      newReviews: reviewStats.total,
      avgRating: reviewStats.avgRating,
      avgResponseTime: 12, // minutes â tracked in production
      postsPublished: postStats.totalPublished,
      totalImpressions: postStats.totalImpressions,
      ctaClicks: postStats.totalClicks,
      ticketsFromGBP: 0, // tracked via UTM in production
      photoViews: 0, // from GBP insights API
    };

    // Generate AI report
    const report = await generateWeeklyReport(metrics);

    // Save snapshot
    saveAnalyticsSnapshot({
      ...metrics,
      aiGrade: report.grade,
      aiSummary: report.summary,
    });

    // Email the report
    const managerEmail = process.env.MANAGER_EMAIL || 'lighthousecinemapg@gmail.com';
    try {
      await sendWeeklyReportEmail(managerEmail, report, metrics);
    } catch (emailErr) {
      console.error('Failed to email weekly report:', emailErr.message);
    }

    return NextResponse.json({
      success: true,
      report,
      metrics,
    });

  } catch (err) {
    console.error('Analytics report error:', err);
    return NextResponse.json({ error: 'Report generation failed' }, { status: 500 });
  }
}

async function sendWeeklyReportEmail(to, report, metrics) {
  const nodemailer = await import('nodemailer');

  const transporter = nodemailer.default.createTransport({
    host: process.env.SMTP_HOST || 'smtp.gmail.com',
    port: parseInt(process.env.SMTP_PORT || '587'),
    secure: false,
    auth: {
      user: process.env.SMTP_USER,
      pass: process.env.SMTP_PASS,
    },
  });

  await transporter.sendMail({
    from: `"CineMax AI" <${process.env.SMTP_USER}>`,
    to,
    subject: `ð Lighthouse Cinema â Weekly GBP Report (Grade: ${report.grade})`,
    html: `
      <div style="font-family:Inter,sans-serif;max-width:600px;margin:0 auto;background:#0A0A0A;color:#FAFAFA;padding:32px;border-radius:12px;">
        <h1 style="color:#C9A84C;font-family:Georgia,serif;">Weekly Performance Report</h1>
        <p style="color:#BCBCBC;">${report.summary}</p>

        <div style="background:#111;border:1px solid #2A2A2A;border-radius:8px;padding:24px;margin:24px 0;">
          <h3 style="color:#C9A84C;margin-top:0;">Key Metrics</h3>
          <p>Reviews: <strong>${metrics.newReviews}</strong> | Avg Rating: <strong>${metrics.avgRating}/5</strong></p>
          <p>Posts Published: <strong>${metrics.postsPublished}</strong> | Impressions: <strong>${metrics.totalImpressions}</strong></p>
          <p>CTA Clicks: <strong>${metrics.ctaClicks}</strong></p>
        </div>

        <div style="background:#111;border:1px solid #2A2A2A;border-radius:8px;padding:24px;margin:24px 0;">
          <h3 style="color:#C9A84C;margin-top:0;">Highlights</h3>
          ${report.highlights.map(h => `<p style="color:#BCBCBC;">â¨ ${h}</p>`).join('')}
        </div>

        <div style="background:#111;border:1px solid #2A2A2A;border-radius:8px;padding:24px;margin:24px 0;">
          <h3 style="color:#C9A84C;margin-top:0;">Recommendations</h3>
          ${report.recommendations.map(r => `<p style="color:#BCBCBC;">â ${r}</p>`).join('')}
        </div>

        <div style="text-align:center;padding:16px;border-top:1px solid #2A2A2A;margin-top:24px;">
          <p style="color:#888;font-size:12px;">Generated by CineMax AI for Lighthouse Cinema</p>
        </div>
      </div>
    `,
  });
}
