// app/admin/schedule/page.js
// Admin Schedule Manager — visual UI for managing movies, showtimes, and ticket links
'use client';

import { useState, useEffect } from 'react';
import { movies as currentMovies, SQUARE_LINKS } from '../../showtime-config';

const gold = '#D4AF37';
const dark = '#0A0A0A';
const darkCard = '#111111';

const DAYS = ['Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'];
const STANDARD_TIMES = ['12:00 PM', '1:00 PM', '2:00 PM', '2:30 PM', '3:00 PM', '4:00 PM', '4:30 PM', '5:00 PM', '5:30 PM', '7:00 PM', '7:30 PM', '9:00 PM', '9:30 PM'];

export default function AdminSchedulePage() {
  const [movieList, setMovieList] = useState([]);
  const [editingMovie, setEditingMovie] = useState(null);
  const [notification, setNotification] = useState('');
  const [activeTab, setActiveTab] = useState('now-playing');

  useEffect(() => {
    setMovieList(currentMovies.map(m => ({ ...m })));
  }, []);

  const showNotif = (msg) => {
    setNotification(msg);
    setTimeout(() => setNotification(''), 3000);
  };

  const toggleActive = (slug) => {
    setMovieList(prev => prev.map(m =>
      m.slug === slug ? { ...m, active: !m.active } : m
    ));
    showNotif('Movie visibility toggled');
  };

  const updateShowtime = (slug, day, times) => {
    setMovieList(prev => prev.map(m => {
      if (m.slug !== slug) return m;
      const newShowtimes = { ...m.showtimes, [day]: times };
      return { ...m, showtimes: newShowtimes };
    }));
  };

  const updateTicketLink = (slug, key, link) => {
    setMovieList(prev => prev.map(m => {
      if (m.slug !== slug) return m;
      const newLinks = { ...m.ticketLinks, [key]: link };
      return { ...m, ticketLinks: newLinks };
    }));
  };

  const generateConfig = () => {
    const configStr = '// Auto-generated by Schedule Manager — ' + new Date().toISOString() + '\n' +
      'export const SQUARE_LINKS = ' + JSON.stringify(SQUARE_LINKS, null, 2) + ';\n\n' +
      'export const movies = ' + JSON.stringify(movieList, null, 2) + ';\n\n' +
      'export function getTicketLink(movie, time) {\n' +
      '  const [hm, period] = time.split(" ");\n' +
      '  const [h, m] = hm.split(":");\n' +
      '  let hour = parseInt(h);\n' +
      '  if (period === "PM" && hour !== 12) hour += 12;\n' +
      '  if (period === "AM" && hour === 12) hour = 0;\n' +
      '  const key = hour + ":" + m;\n' +
      '  if (!movie.ticketLinks) return SQUARE_LINKS.general;\n' +
      '  return movie.ticketLinks[key] || movie.ticketLinks.default || SQUARE_LINKS.general;\n' +
      '}\n\n' +
      'export function isMovieActive(movie) {\n' +
      '  if (!movie.active) return false;\n' +
      '  const today = new Date().toISOString().split("T")[0];\n' +
      '  if (movie.startDate && today < movie.startDate) return false;\n' +
      '  if (movie.endDate && today > movie.endDate) return false;\n' +
      '  return true;\n' +
      '}\n\n' +
      'export function isComingSoon(movie) {\n' +
      '  if (!movie.active) return false;\n' +
      '  const today = new Date().toISOString().split("T")[0];\n' +
      '  return movie.startDate && today < movie.startDate;\n' +
      '}';
    return configStr;
  };

  const saveToGitHub = async () => {
    const config = generateConfig();
    try {
      const getRes = await fetch(
        'https://api.github.com/repos/lighthousecinemapg-cyber/lighthouse-cinema/contents/app/showtime-config.js',
        { headers: { 'Accept': 'application/vnd.github.v3+json' } }
      );
      const fileData = await getRes.json();
      const updateRes = await fetch(
        'https://api.github.com/repos/lighthousecinemapg-cyber/lighthouse-cinema/contents/app/showtime-config.js',
        {
          method: 'PUT',
          headers: {
            'Accept': 'application/vnd.github.v3+json',
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({
            message: 'Schedule update — ' + new Date().toLocaleDateString(),
            content: btoa(unescape(encodeURIComponent(config))),
            sha: fileData.sha,
          })
        }
      );
      if (updateRes.ok) {
        showNotif('Schedule saved to GitHub! Site will auto-deploy in ~30 seconds.');
      } else {
        throw new Error('GitHub API error');
      }
    } catch (e) {
      const blob = new Blob([config], { type: 'text/javascript' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = 'showtime-config.js';
      a.click();
      showNotif('Config downloaded — upload to GitHub to deploy.');
    }
  };

  const filteredMovies = movieList.filter(m => {
    if (activeTab === 'now-playing') return m.status === 'now-playing' || m.status === 'classic' || m.status === 'special-screening';
    if (activeTab === 'coming-soon') return m.status === 'coming-soon';
    return true;
  });

  const todayStr = new Date().toISOString().split('T')[0];
  const dayOfWeek = new Date().toLocaleDateString('en-US', { weekday: 'long' });

  return (
    <div style={{ minHeight: '100vh', background: dark, color: '#fff', fontFamily: 'Inter, sans-serif' }}>
      {/* Header */}
      <div style={{ background: darkCard, borderBottom: '2px solid ' + gold, padding: '20px 40px', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <div>
          <h1 style={{ color: gold, fontSize: '28px', margin: 0, fontFamily: 'Playfair Display, serif' }}>
            Schedule Manager
          </h1>
          <p style={{ color: '#888', margin: '4px 0 0', fontSize: '14px' }}>
            {dayOfWeek}, {new Date().toLocaleDateString()} — Changes auto-deploy to lighthousepgcinema.com
          </p>
        </div>
        <div style={{ display: 'flex', gap: '12px' }}>
          <button onClick={saveToGitHub} style={{
            background: gold, color: dark, border: 'none', padding: '12px 24px',
            borderRadius: '8px', fontWeight: 'bold', cursor: 'pointer', fontSize: '16px'
          }}>
            Save & Deploy
          </button>
        </div>
      </div>

      {notification && (
        <div style={{ background: '#1a472a', color: '#4ade80', padding: '12px 40px', textAlign: 'center', fontWeight: 'bold' }}>
          {notification}
        </div>
      )}

      {/* Tabs */}
      <div style={{ padding: '20px 40px', display: 'flex', gap: '12px' }}>
        {['now-playing', 'coming-soon', 'all'].map(tab => (
          <button key={tab} onClick={() => setActiveTab(tab)} style={{
            background: activeTab === tab ? gold : '#222',
            color: activeTab === tab ? dark : '#888',
            border: 'none', padding: '10px 20px', borderRadius: '6px',
            cursor: 'pointer', fontWeight: 'bold', textTransform: 'capitalize',
          }}>
            {tab.replace('-', ' ')}
          </button>
        ))}
      </div>

      {/* Movie Cards */}
      <div style={{ padding: '0 40px 40px' }}>
        {filteredMovies.map(movie => (
          <div key={movie.slug} style={{
            background: darkCard, borderRadius: '12px', marginBottom: '20px',
            border: movie.active ? '1px solid ' + gold + '40' : '1px solid #333',
            opacity: movie.active ? 1 : 0.5,
            overflow: 'hidden',
          }}>
            <div style={{ display: 'flex', padding: '20px', gap: '20px', alignItems: 'flex-start' }}>
              {/* Poster */}
              <img src={movie.poster} alt={movie.title} style={{
                width: '100px', height: '150px', objectFit: 'cover', borderRadius: '8px',
              }} />

              {/* Info */}
              <div style={{ flex: 1 }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                  <h2 style={{ color: gold, margin: 0, fontSize: '22px' }}>{movie.title}</h2>
                  <div style={{ display: 'flex', gap: '8px', alignItems: 'center' }}>
                    <span style={{
                      background: movie.active ? '#1a472a' : '#472a1a',
                      color: movie.active ? '#4ade80' : '#f87171',
                      padding: '4px 12px', borderRadius: '20px', fontSize: '12px', fontWeight: 'bold',
                    }}>
                      {movie.active ? 'ACTIVE' : 'HIDDEN'}
                    </span>
                    <button onClick={() => toggleActive(movie.slug)} style={{
                      background: '#333', color: '#fff', border: 'none', padding: '6px 12px',
                      borderRadius: '6px', cursor: 'pointer', fontSize: '12px',
                    }}>
                      {movie.active ? 'Hide' : 'Show'}
                    </button>
                    <button onClick={() => setEditingMovie(editingMovie === movie.slug ? null : movie.slug)} style={{
                      background: gold, color: dark, border: 'none', padding: '6px 12px',
                      borderRadius: '6px', cursor: 'pointer', fontSize: '12px', fontWeight: 'bold',
                    }}>
                      {editingMovie === movie.slug ? 'Close' : 'Edit'}
                    </button>
                  </div>
                </div>
                <p style={{ color: '#888', margin: '4px 0', fontSize: '14px' }}>
                  {movie.rating} {movie.runtime ? '\u2022 ' + movie.runtime : ''} \u2022 {movie.genre}
                  {movie.rottenTomatoes ? ' \u2022 \ud83c\udf45 ' + movie.rottenTomatoes : ''}
                </p>
                {movie.displayNote && (
                  <p style={{ color: gold, margin: '4px 0', fontSize: '13px', fontStyle: 'italic' }}>
                    {movie.displayNote}
                  </p>
                )}

                {/* Today Showtimes Quick View */}
                {movie.showtimes && movie.showtimes[dayOfWeek] && (
                  <div style={{ marginTop: '8px' }}>
                    <span style={{ color: '#888', fontSize: '12px' }}>Today: </span>
                    {movie.showtimes[dayOfWeek].map(t => (
                      <span key={t} style={{
                        background: '#222', color: gold, padding: '2px 10px',
                        borderRadius: '4px', marginRight: '6px', fontSize: '13px',
                      }}>{t}</span>
                    ))}
                  </div>
                )}

                {/* Ticket Link */}
                <div style={{ marginTop: '8px', fontSize: '12px', color: '#666' }}>
                  Ticket: {movie.ticketLinks?.default || SQUARE_LINKS.general}
                </div>
              </div>
            </div>

            {/* Expanded Edit Panel */}
            {editingMovie === movie.slug && (
              <div style={{ borderTop: '1px solid #333', padding: '20px', background: '#0d0d0d' }}>
                <h3 style={{ color: gold, marginTop: 0 }}>Edit Showtimes</h3>

                {movie.showtimes && (
                  <div style={{ display: 'grid', gridTemplateColumns: 'repeat(5, 1fr)', gap: '12px' }}>
                    {DAYS.map(day => (
                      <div key={day}>
                        <label style={{ color: '#888', fontSize: '12px', fontWeight: 'bold', display: 'block', marginBottom: '6px' }}>
                          {day}
                        </label>
                        {STANDARD_TIMES.map(time => {
                          const isSelected = movie.showtimes[day]?.includes(time);
                          return (
                            <button key={time} onClick={() => {
                              const current = movie.showtimes[day] || [];
                              const updated = isSelected
                                ? current.filter(t => t !== time)
                                : [...current, time].sort();
                              updateShowtime(movie.slug, day, updated);
                            }} style={{
                              display: 'block', width: '100%', marginBottom: '4px',
                              background: isSelected ? gold : '#1a1a1a',
                              color: isSelected ? dark : '#666',
                              border: '1px solid ' + (isSelected ? gold : '#333'),
                              padding: '4px 8px', borderRadius: '4px', cursor: 'pointer',
                              fontSize: '12px', fontWeight: isSelected ? 'bold' : 'normal',
                            }}>
                              {time}
                            </button>
                          );
                        })}
                      </div>
                    ))}
                  </div>
                )}

                <h3 style={{ color: gold, marginTop: '20px' }}>Ticket Links</h3>
                <div style={{ display: 'flex', gap: '12px', alignItems: 'center' }}>
                  <label style={{ color: '#888', fontSize: '13px', minWidth: '80px' }}>Default:</label>
                  <input
                    type="text"
                    value={movie.ticketLinks?.default || ''}
                    onChange={e => updateTicketLink(movie.slug, 'default', e.target.value)}
                    style={{
                      flex: 1, background: '#1a1a1a', border: '1px solid #333', color: '#fff',
                      padding: '8px 12px', borderRadius: '6px', fontSize: '13px',
                    }}
                    placeholder="https://square.link/u/..."
                  />
                </div>

                <h3 style={{ color: gold, marginTop: '20px' }}>Movie Details</h3>
                <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '12px' }}>
                  <div>
                    <label style={{ color: '#888', fontSize: '12px', display: 'block' }}>Start Date</label>
                    <input type="date" value={movie.startDate || ''} onChange={e => {
                      setMovieList(prev => prev.map(m => m.slug === movie.slug ? { ...m, startDate: e.target.value } : m));
                    }} style={{ width: '100%', background: '#1a1a1a', border: '1px solid #333', color: '#fff', padding: '8px', borderRadius: '6px' }} />
                  </div>
                  <div>
                    <label style={{ color: '#888', fontSize: '12px', display: 'block' }}>End Date</label>
                    <input type="date" value={movie.endDate || ''} onChange={e => {
                      setMovieList(prev => prev.map(m => m.slug === movie.slug ? { ...m, endDate: e.target.value || null } : m));
                    }} style={{ width: '100%', background: '#1a1a1a', border: '1px solid #333', color: '#fff', padding: '8px', borderRadius: '6px' }} />
                  </div>
                  <div>
                    <label style={{ color: '#888', fontSize: '12px', display: 'block' }}>Display Note</label>
                    <input type="text" value={movie.displayNote || ''} onChange={e => {
                      setMovieList(prev => prev.map(m => m.slug === movie.slug ? { ...m, displayNote: e.target.value } : m));
                    }} style={{ width: '100%', background: '#1a1a1a', border: '1px solid #333', color: '#fff', padding: '8px', borderRadius: '6px' }} />
                  </div>
                  <div>
                    <label style={{ color: '#888', fontSize: '12px', display: 'block' }}>Status</label>
                    <select value={movie.status} onChange={e => {
                      setMovieList(prev => prev.map(m => m.slug === movie.slug ? { ...m, status: e.target.value } : m));
                    }} style={{ width: '100%', background: '#1a1a1a', border: '1px solid #333', color: '#fff', padding: '8px', borderRadius: '6px' }}>
                      <option value="now-playing">Now Playing</option>
                      <option value="coming-soon">Coming Soon</option>
                      <option value="classic">Classic</option>
                      <option value="special-screening">Special Screening</option>
                    </select>
                  </div>
                </div>
              </div>
            )}
          </div>
        ))}
      </div>
    </div>
  );
}
